apiVersion: v1
kind: PersistentVolume
metadata:
  name: keyword-spotter-model-storage-volume
  labels:
    type: standard
    language: tensorflow
    service: tfserving
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/quanla/Work/projects/keyword-spotter"
