apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keyword-spotter-model-storage
  namespace: kubeflow-user-example-com
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: standard
      language: tensorflow
      service: tfserving
